[UT03-817] Fix/after login redirect to the main page
pulilab/TIIP pull request #397
Opened 2022-03-02 13:03 UTC by GergelyKovach

# Description

## UT03-859 - Investigation of login redirect error

From the top navigation bar we can clearly see that multiple menu items have the _nuxt-active-link_ class, which is assigned to the links that represent the current[ page](https://github.com/nuxt/nuxt.js/issues/2214#:~:text=The%20default%20active%20class%20matching%20behavior%20is%20inclusive%20match).

![](https://paper-attachments.dropbox.com/s_114E13E6F4F574F233E23E739D7E75FE0DC8B5EFFCC683570C197D2C8931D5A4_1646225236693_image-20220211-141141.png)

This happens because the redirection after login goes to a page the is not handled correctly. Currently the `this.$route.query.next` parameter containes the next page that the user should land on:

![](https://paper-attachments.dropbox.com/s_114E13E6F4F574F233E23E739D7E75FE0DC8B5EFFCC683570C197D2C8931D5A4_1646225193610_image.png)

But there is no indication in any part of the codebase / documentation or PR-s that we should handle anything else than landing on the main index page.
The current solution most likely got an invalid `this.$route.query.next` parameter, as the _nuxt-active-link_ because this class is assigned to all links on the page[ by an inclusive match](https://github.com/nuxt/nuxt.js/issues/2214#:~:text=The%20default%20active%20class%20matching%20behavior%20is%20inclusive%20match.)

![](https://paper-attachments.dropbox.com/s_114E13E6F4F574F233E23E739D7E75FE0DC8B5EFFCC683570C197D2C8931D5A4_1646225404973_image.png)

As we can see the code is quite ambiguous, and its unclear for what exact functionality it was separated into either go to the `this.$route.query.next` callback url (which is most likely faulty) or to the inventory list.

The actual error might be reproduced by going to this link
`http://localhost:3000/en/auth/`

![](https://paper-attachments.dropbox.com/s_114E13E6F4F574F233E23E739D7E75FE0DC8B5EFFCC683570C197D2C8931D5A4_1646225791499_image.png)

The solution addresses this error, and shields from future faulty login experiences.
Simplifying the login to this workflow:

on successful login (through current SSO or email+password login) → going to the main page

Fixes # [UT03-817 (issue)](https://pulilab.atlassian.net/browse/UT03-817)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Locally with several combinations to avoid future occurance

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-03-02 14:09 UTC, nullcode commented
@GergelyKovach this ain't right since you are removing the feature of next.

The next is working, try it in incognito. 
1. Copy paste an URL (eg. portfolio page) when u are logged in 
2. Open incognito and try this URL
It will redirect to login with the next param filled
3. login
4. after logged in it will redirect back to the portfolio page automatically

2022-03-02 14:10 UTC, nullcode requested changes
do not remove the next feature

2022-03-03 00:34 UTC, TiborPL approved these changes

2022-03-03 13:46 UTC, GergelyKovach commented
@nullcode the next query param is reinstated and i extensively tested on different possible scenarios, and also considering the occuring bug that lands the logged in user on a page with all top links bold

2022-03-04 15:30 UTC, nullcode approved these changes

2022-03-04 15:30 UTC, merged