[UT03-923] Feat/refining with forked celery export plugin
pulilab/TIIP pull request #410
Opened 2022-03-21 15:00 UTC by GergelyKovach

# Description

Several minor changes as described in [UT03-923](https://pulilab.atlassian.net/browse/UT03-923)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Locally with console email. And locally with  `fab cov` and `fab lint`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-03-22 14:32 UTC, nullcode requested changes

2022-03-22 14:32 UTC, nullcode commented on django/tiip/settings.py
> +DEFAULT_FROM_EMAIL = env.str('DEFAULT_FROM_EMAIL', default='invent@unicef.org')
why did you change these? please revert to original. open source should not have any invent reference

2022-03-23 10:36 UTC, GergelyKovach commented on django/tiip/settings.py
> +DEFAULT_FROM_EMAIL = env.str('DEFAULT_FROM_EMAIL', default='invent@unicef.org')
changed back
i'll keep in mind opensource-ness

2022-03-24 14:01 UTC, nullcode requested changes

2022-03-24 14:01 UTC, nullcode commented on django/core/admin/__init__.py
> +# extending the exclude list
remove comment

2022-03-24 14:01 UTC, nullcode commented on django/core/admin/__init__.py
> +        # "app_label",
remove commented lines

2022-03-24 14:06 UTC, GergelyKovach commented on django/core/admin/__init__.py
> +# extending the exclude list
this might be unclear why we redefine the ExportJobAdmin

2022-03-24 14:07 UTC, GergelyKovach commented on django/core/admin/__init__.py
> +        # "app_label",
as its an override of default state i feel this is useful if in the future its reactivated

2022-03-24 14:07 UTC, GergelyKovach commented on django/core/admin/__init__.py
> +# extending the exclude list
resolved: removed the comments

2022-03-24 14:08 UTC, GergelyKovach commented on django/core/admin/__init__.py
> +        # "app_label",
resolved: removed the comments

2022-03-24 17:18 UTC, nullcode approved these changes

2022-03-24 17:18 UTC, merged