[UT03-932][UT03-944][UT03-945][UT03-946] Feat/introducing landscape review
pulilab/TIIP pull request #413
Opened 2022-03-28 13:46 UTC by GergelyKovach

# Description

Inroducing `landscape_review` field in the admin, api and export fields

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Locally with unit tests and linter

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-03-28 14:17 UTC, nullcode requested changes
missing KPI stuff, look at kpi app and serializers

2022-03-29 09:14 UTC, nullcode requested changes

2022-03-29 09:14 UTC, nullcode commented on django/kpi/tests.py
> +        self.assertEqual(Portfolio.objects.get(id=self.port1_resp.json()['id']).landscape_review, False)
these are not testing the snapshots, just getting the portfolio object. you need to test that the snapshots include the landscape review and see if they change if u change it.
look at `past_snapshot['portfolios'][1]['investment_to_date']` test for example

2022-03-29 09:14 UTC, nullcode commented on django/kpi/tests.py
> +        self.assertEqual(Portfolio.objects.get(id=self.port2_resp.json()['id']).landscape_review, False)
same as above

2022-03-29 09:14 UTC, nullcode commented on django/project/tests/portfolio_tests.py
> +        self.assertEqual(Portfolio.objects.get(id=response.json()['id']).landscape_review, False)
same as above

2022-03-29 09:32 UTC, GergelyKovach commented on django/kpi/tests.py
> +        self.assertEqual(Portfolio.objects.get(id=self.port2_resp.json()['id']).landscape_review, False)
done ✅

2022-03-29 10:32 UTC, nullcode approved these changes

2022-03-29 10:32 UTC, merged